import {resolve} from "node:path";
import {type CapturedFrame, TextAttributes} from "@opentui/core";
import {createTestRenderer, setRendererCapabilities} from "@opentui/core/testing";
import {blupostMarkPng} from "../src/tui/brandAsset.js";
import {createBlupostTui} from "../src/tui/index.js";
import {minimalMessagingFixture} from "../tests/support/minimalMessagingFixture.js";
import {RecordingEngineClient} from "../tests/support/recordingEngineClient.js";

const [columnsArgument, rowsArgument, outputArgument] = process.argv.slice(2);
const columns = Number(columnsArgument ?? 120);
const rows = Number(rowsArgument ?? 34);
if (!Number.isInteger(columns) || columns < 1 || !Number.isInteger(rows) || rows < 1) {
  throw new Error("usage: generate-ui-preview.ts [columns rows [output.svg]]");
}
const cellWidth = 9;
const cellHeight = 18;
const inset = 18;
const canvasWidth = columns * cellWidth + inset * 2;
const canvasHeight = rows * cellHeight + inset * 2;

function escapeXml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function hex(red: number, green: number, blue: number): string {
  return `#${[red, green, blue]
    .map(channel => channel.toString(16).padStart(2, "0"))
    .join("")}`;
}

interface BrandPlacement {
  x: number;
  y: number;
  width: number;
  height: number;
}

function frameToSvg(frame: CapturedFrame, brand: BrandPlacement): string {
  const body: string[] = [];
  for (const [row, line] of frame.lines.entries()) {
    let column = 0;
    for (const span of line.spans) {
      const width = span.width * cellWidth;
      const attributes = span.attributes & 0xff;
      let [fgRed, fgGreen, fgBlue] = span.fg.toInts();
      let [bgRed, bgGreen, bgBlue] = span.bg.toInts();
      if (attributes & TextAttributes.INVERSE) {
        [fgRed, bgRed] = [bgRed, fgRed];
        [fgGreen, bgGreen] = [bgGreen, fgGreen];
        [fgBlue, bgBlue] = [bgBlue, fgBlue];
      }
      const x = inset + column * cellWidth;
      const y = inset + row * cellHeight;
      body.push(
        `    <rect x="${x}" y="${y}" width="${width}" height="${cellHeight}" fill="${hex(bgRed, bgGreen, bgBlue)}"/>`
      );
      if (span.text.trim() && !(attributes & TextAttributes.HIDDEN) && span.fg.a > 0) {
        const decorations = [
          attributes & TextAttributes.UNDERLINE ? "underline" : "",
          attributes & TextAttributes.STRIKETHROUGH ? "line-through" : ""
        ]
          .filter(Boolean)
          .join(" ");
        body.push(
          `    <text x="${x}" y="${y + 14}" fill="${hex(fgRed, fgGreen, fgBlue)}" font-weight="${attributes & TextAttributes.BOLD ? 700 : 450}"${attributes & TextAttributes.ITALIC ? ' font-style="italic"' : ""}${decorations ? ` text-decoration="${decorations}"` : ""} textLength="${width}" lengthAdjust="spacingAndGlyphs">${escapeXml(span.text)}</text>`
        );
      }
      column += span.width;
    }
  }

  const brandX = inset + brand.x * cellWidth;
  const brandY = inset + brand.y * cellHeight;
  const brandWidth = brand.width * cellWidth;
  const brandHeight = brand.height * cellHeight;
  body.push(
    `    <rect x="${brandX}" y="${brandY}" width="${brandWidth}" height="${brandHeight}" fill="#151a21"/>`
  );
  body.push(
    `    <image x="${brandX}" y="${brandY}" width="${brandWidth}" height="${brandHeight}" href="data:image/png;base64,${blupostMarkPng.toString("base64")}" preserveAspectRatio="xMidYMid meet"/>`
  );

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${canvasWidth}" height="${canvasHeight}" viewBox="0 0 ${canvasWidth} ${canvasHeight}" role="img" aria-labelledby="title description">
  <title id="title">Electric-blue Blupost messaging interface at ${columns}x${rows}</title>
  <desc id="description">An authentic deterministic frame captured from the implemented Blupost terminal interface.</desc>
  <!-- authentic deterministic frame; generated by scripts/generate-ui-preview.ts -->
  <rect width="${canvasWidth}" height="${canvasHeight}" rx="14" fill="#080a0d"/>
  <defs>
    <clipPath id="terminal-clip"><rect x="${inset}" y="${inset}" width="${columns * cellWidth}" height="${rows * cellHeight}" rx="4"/></clipPath>
  </defs>
  <g clip-path="url(#terminal-clip)" font-family="'Geist Mono', 'JetBrains Mono', 'Cascadia Mono', monospace" font-size="14" xml:space="preserve">
${body.join("\n")}
  </g>
</svg>
`;
}

const setup = await createTestRenderer({width: columns, height: rows});
setRendererCapabilities(setup.renderer, {
  kitty_graphics: true,
  rgb: true,
  image_protocol: "kitty",
  terminal: {name: "kitty"}
});
const engine = new RecordingEngineClient(minimalMessagingFixture());
const app = createBlupostTui({
  renderer: setup.renderer,
  engine,
  autoConnect: false
});

try {
  await app.start();
  await setup.renderOnce();
  const output = outputArgument
    ? resolve(outputArgument)
    : resolve(import.meta.dir, "../docs/ui-preview.svg");
  const brand = [
    setup.renderer.root.findDescendantById("brand-mark"),
    setup.renderer.root.findDescendantById("compact-brand-mark")
  ].find(candidate => candidate?.visible);
  if (!brand?.visible) throw new Error("visible brand mark was not rendered");
  await Bun.write(
    output,
    frameToSvg(setup.captureSpans(), {
      x: brand.screenX,
      y: brand.screenY,
      width: brand.width,
      height: brand.height
    })
  );
  console.log(`wrote ${output}`);
} finally {
  await app.stop();
}
